In [3]:
import numpy as np

an_arr = np.array([1,2,3])
print(an_arr)
print(type(an_arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
print(an_arr.shape)

(3,)


In [5]:
print(an_arr[0], an_arr[1], an_arr[2])

1 2 3


In [6]:
an_arr[1] =  4

print(an_arr)

[1 4 3]


In [9]:
another = np.array([[1,2,3],[4,5,6]])

print(another)
print(another[0,1], another[0,0])
print(another.shape)

[[1 2 3]
 [4 5 6]]
2 1
(2, 3)


In [11]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [13]:
ex2 = np.full((4,5), 8.5)
print(ex2)

[[8.5 8.5 8.5 8.5 8.5]
 [8.5 8.5 8.5 8.5 8.5]
 [8.5 8.5 8.5 8.5 8.5]
 [8.5 8.5 8.5 8.5 8.5]]


In [15]:
ex3 = np.eye(2,3)
print(ex3)

[[1. 0. 0.]
 [0. 1. 0.]]


In [18]:
ex4 = np.ones((2,3))
print(ex4)
print()
print(ex4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]

(2, 3)


In [19]:
ex5 = np.random.random((4,4))
print(ex5)

[[0.09029735 0.70744925 0.78828431 0.23485556]
 [0.35460865 0.43558095 0.01666971 0.07537923]
 [0.26476269 0.55568064 0.46747447 0.17202602]
 [0.33384832 0.23433065 0.50579619 0.90259466]]


In [20]:
an_arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(an_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
a_slice = an_arr[:2,1:4]
print(a_slice)
b_slice = np.array(an_arr[:2,1:4])
print(b_slice)

[[200   3   4]
 [  7   8   9]]
[[200   3   4]
 [  7   8   9]]


In [24]:
print('Before', an_arr[0,1])
a_slice[0,0] = 200
print('After', an_arr[0,1])
print('Before', an_arr[0,1])
b_slice[0,0] = 20
print('Now', an_arr[0,1])

Before 200
After 200
Before 200
Now 200


In [25]:
row_rank1 = an_arr[1,:]
print(row_rank1, row_rank1.shape)

[ 6  7  8  9 10] (5,)


In [26]:
row_rank2 = an_arr[1:2,:]
print(row_rank2, row_rank2.shape)

[[ 6  7  8  9 10]] (1, 5)


In [27]:
col_rank1 = an_arr[:,1]
col_rank2 = an_arr[:,1:2]
print(col_rank1, col_rank1.shape)
print(col_rank2, col_rank2.shape)

[200   7  12] (3,)
[[200]
 [  7]
 [ 12]] (3, 1)


In [28]:
an_arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print("Original", an_arr)

Original [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [29]:
col_indices = np.array([0,1,2,0])
row_indices = np.arange(4)
print(col_indices)
print(row_indices)

[0 1 2 0]
[0 1 2 3]


In [30]:
for row, col in zip(row_indices,col_indices):
    print(row," ,",col)

0  , 0
1  , 1
2  , 2
3  , 0


In [31]:
print(an_arr[row_indices,col_indices])

[ 1  7 13 16]


In [32]:
an_arr[row_indices,col_indices] += 10000
print(an_arr)

[[10001     2     3     4     5]
 [    6 10007     8     9    10]
 [   11    12 10013    14    15]
 [10016    17    18    19    20]]


In [33]:
an_arr = np.array([[1,2],[3,4],[5,6]])
print(an_arr)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
filter = (an_arr > 2)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [36]:
print(an_arr[filter])

[3 4 5 6]


In [38]:
an_arr[an_arr > 2]

array([3, 4, 5, 6])

In [40]:
an_arr[(an_arr > 2)& (an_arr < 5)]

array([3, 4])

In [41]:
an_arr[(an_arr % 2 == 1)]

array([1, 3, 5])

In [43]:
an_arr[(an_arr % 2 == 1)] += 50
print(an_arr)

[[101   2]
 [103   4]
 [105   6]]


In [44]:
ex1 = np.array([11,1])
print(ex1.dtype)

int64


In [45]:
ex2 = np.array([11.0, 1.0])
print(ex2.dtype)

float64


In [47]:
ex3 =np.array([1,2], dtype=np.float64)
print(ex3)

[1. 2.]


In [49]:
ex4 = np.array([12.1,1.2], dtype=np.int64)
print(ex4)

[12  1]


In [3]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5.1,6.1],[7.1,8.1]], dtype = np.float64)
print(x)
print(y)

[[1 2]
 [3 4]]
[[5.1 6.1]
 [7.1 8.1]]


In [4]:
print(x + y)
print(np.add(x,y))

[[ 6.1  8.1]
 [10.1 12.1]]
[[ 6.1  8.1]
 [10.1 12.1]]


In [6]:
print(x-y)
print(np.subtract(x,y))

[[-4.1 -4.1]
 [-4.1 -4.1]]
[[-4.1 -4.1]
 [-4.1 -4.1]]


In [7]:
print(x*y)
print(np.multiply(x,y))

[[ 5.1 12.2]
 [21.3 32.4]]
[[ 5.1 12.2]
 [21.3 32.4]]


In [8]:
print(x/y)
print(np.divide(x,y))

[[0.19607843 0.32786885]
 [0.42253521 0.49382716]]
[[0.19607843 0.32786885]
 [0.42253521 0.49382716]]


In [9]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [10]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [12]:
arr = 10 * np.random.randn(2,5)
print(arr)

[[-26.87267703  -9.12955202  14.58956472 -25.77591753   4.86177424]
 [-10.93356351  17.1420467   -2.10712664  12.35454514   3.95348188]]


In [13]:
print(arr.mean())

-2.1917424049862353


In [14]:
print(arr.mean(axis=1))

[-8.46536152  4.08187671]


In [15]:
print(arr.mean(axis=0))

[-18.90312027   4.00624734   6.24121904  -6.7106862    4.40762806]


In [16]:
print(arr.sum())

-21.917424049862355


In [17]:
print(np.median(arr,axis=1))

[-9.12955202  3.95348188]


In [18]:
print(np.median(arr,axis=0))

[-18.90312027   4.00624734   6.24121904  -6.7106862    4.40762806]


In [19]:
unsorted = np.random.randn(10)
print(unsorted)

[-2.54346044 -1.44711977  0.6271207  -0.54440486 -1.45906255  0.36004901
  1.05279072 -0.85216511 -0.78904882 -0.76824529]


In [20]:
sorted1 = np.array(unsorted)
sorted1.sort()
print(sorted1)
print(unsorted)

[-2.54346044 -1.45906255 -1.44711977 -0.85216511 -0.78904882 -0.76824529
 -0.54440486  0.36004901  0.6271207   1.05279072]
[-2.54346044 -1.44711977  0.6271207  -0.54440486 -1.45906255  0.36004901
  1.05279072 -0.85216511 -0.78904882 -0.76824529]


In [21]:
unsorted.sort()
print(unsorted)

[-2.54346044 -1.45906255 -1.44711977 -0.85216511 -0.78904882 -0.76824529
 -0.54440486  0.36004901  0.6271207   1.05279072]


In [22]:
array = np.array([1,2,1,4,2,1,3,2])

print(np.unique(array))

[1 2 3 4]


In [24]:
s1 = np.array(['desk','bulb','chair'])
s2 = np.array(['ball','chair','lamp'])
print(s1,s2)

['desk' 'bulb' 'chair'] ['ball' 'chair' 'lamp']


In [25]:
print(np.intersect1d(s1,s2))

['chair']


In [26]:
print(np.union1d(s1,s2))

['ball' 'bulb' 'chair' 'desk' 'lamp']


In [27]:
print(np.setdiff1d(s1,s2))

['bulb' 'desk']


In [28]:
print(np.setdiff1d(s2,s1))

['ball' 'lamp']


In [29]:
print(np.in1d(s1,s2))

[False False  True]


In [31]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [33]:
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [35]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [36]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [37]:
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
from numpy import arange
from timeit import Timer

In [39]:
size = 20000000
timeits = 2000

In [40]:
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [44]:
timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")

print("Time taken by numpy: %f"%(timer_numpy.timeit(timeits)/timeits))

Time taken by numpy: 0.019680


In [45]:
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [46]:
timer_list = Timer("sum(a_list)","from __main__ import a_list")

print("Time taken by list: %f"%(timer_numpy.timeit(timeits)/timeits))

Time taken by list: 0.028965
